<?php

namespace Tests\Unit\Models\Draftpicks;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Psr\Log\NullLogger;
use Tests\TestCase;

class DraftpicksTest extends TestCase
{
    use WithFaker;
    use RefreshDatabase;

    function it_shows_drivers()
    {
        //given

        //when
        //$this->artisan();

        //then

    }

    /** @test  */
    function it_has_draftpicks_table() {
        $data = [
            'draftId' => $this->faker->numberBetween(1,119)
        ];
        $this->assertDatabaseHas('draftpicks', $data);
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan(' migrate --path=/database/migrations/2021_02_06_195021_create_draftpicks_table.php');
        $this->seed(\DraftpicksTableSeeder::class);
    }
}
