<?php namespace Tests\Unit\Models\Constructors;

use App\Models\Constructors;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;

class ConstructorsTest extends TestCase {
    use WithFaker;
    use RefreshDatabase;

    /** @test  */
    public function testGetConstructorsResults()
    {
        $this->assertIsBool(true);
    }

    /** @test  */
    public function seeder_test() {
        //$this->seed(\ConstructorsTableSeeder::class);
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed');

    }
}
