<?php namespace Tests\Unit\Models\drivers;

use App\Models\Person\Driver;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class DriverTest extends TestCase
{
    use WithFaker;
    use RefreshDatabase;

    function it_shows_drivers()
    {
        //given

        //when
        //$this->artisan();

        //then

    }
    /** @test  */
    function it_has_driver_table() {
        $data = [
            'driverId' => '1'
        ];
        $this->assertDatabaseHas('drivers', $data);
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan(' migrate --path=/database/migrations/2021_02_07_174201_create_drivers_table.php');
        $this->seed(\DriversTableSeeder::class);
    }

}
