<?php namespace Tests\Unit\Models\clients;

use App\Models\Clients\TeamManager;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;

class TeamManagerTest extends TestCase {
    use WithFaker;
    use RefreshDatabase;
    //use DatabaseMigrations;

    /** @test  */
    public function a_simple_test() {
        $this->withoutExceptionHandling();
        $attributesForTable = [
            'teamOwnerId' => 1
        ];
        $this->assertDatabasehas('teammanagers',$attributesForTable);
    }
    /** @test */
    public function a_get_test() {
        $this->withoutExceptionHandling();
    $aft = [
        //'teamOwnerId' => '3',
        'firstName' => 'Trey',
        'lastName' => 'Causey',
        'dob' => '1981-03-27',
        'handle' => 'tomato'
    ];
    $this->get('teamManagers/index', $aft);
    $this->assertDatabaseHas('teammanagers', $aft);
    }

    /** @test */
    public function a_user_can_create_teammanagers() {
        $this->withoutExceptionHandling();

        $attributes = [
            'teamOwnerId' => 8,
            'firstName' => 'trey',
            'lastName' => 'causey',
            'dob' => '03-03-1999',
            'handle' => 'xxx'
        ];
        $this->post('/teamManagers/index', $attributes)->assertRedirect('/teamManagers/index');

        $this->assertDatabaseHas('teammanagers', $attributes);

        $this->get('/teamManagers/index')->assertSee($attributes['teamOwnerId']);
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan(' migrate --path=/database/migrations/2021_02_05_071724_create_teammanagers_table.php');
        $this->seed(\TeammanagersTableSeeder::class);
    }
}
